# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Adobe.Acrobat.Reader.64-bit
PackageVersion: 21.007.20099
PackageDescription: A PDF Reader for Windows
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallPath: C:\Program Files\Adobe\Acrobat Reader DC\Reader
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /sAll /rs /rps /l /re
  SilentWithProgress: /sAll /rs /rps /l /re
UpgradeBehavior: install
FileExtensions:
- pdf
- pdfa
- pdfx
- xfx
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_en_US.exe
  InstallerSha256: 5C96988674B82E22DEC0F2C7DDED08D2E299328BD26F55B241529B879FA819E4
ManifestType: installer
ManifestVersion: 1.0.0