# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 96.0.4664.45
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 0A170040F944A81C9AF8CDE8D46AC22E35A19A4047AF02C49BEEF09EAA4959F1
  ProductCode: '{27AE757E-4286-3D70-ACB1-4FEAC2F15FB9}'
ManifestType: installer
ManifestVersion: 1.0.0